from pathlib import Path
from PyQt6.QtGui import QColor

ASSETS = Path(__file__).parent / "assets"

# brand colors
NAVY = QColor("#1B2447")
TWILIGHT = QColor("#3D4A7A")
AIR_BLUE = QColor("#718CA0")
LAVENDER = QColor("#E8E6F0")
BLOSSOM = QColor("#E5B8CF")
WHITE = QColor("#FFFFFF")

BLOSSOM_HOVER = "#eec6dc"
SECONDARY_BUTTON_BG = "rgba(255,255,255,140)"
SECONDARY_BUTTON_HOVER = "rgba(255,255,255,200)"

SHADOW_COLOR_R = 27
SHADOW_COLOR_G = 36
SHADOW_COLOR_B = 71
SESSION_SHADOW_ALPHA = 230
TIME_SHADOW_ALPHA = 220
PANEL_ALPHA = 90

# timing
FOCUS_MINUTES = 25
BREAK_MINUTES = 5
SECONDS_PER_MINUTE = 60
FOCUS_SECONDS = FOCUS_MINUTES * SECONDS_PER_MINUTE
BREAK_SECONDS = BREAK_MINUTES * SECONDS_PER_MINUTE
TICK_INTERVAL_MS = 1000

# window
WINDOW_TITLE = "tar0bunny Code & Chill Pomodoro"
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 580
APP_STYLE = "Fusion"

# fonts
FONT_FAMILY = "Century Gothic"
FONT_FAMILY_SANS = "sans-serif"
LABEL_FONT_FAMILY = "Gabriola"
SESSION_FONT_SIZE = 27
TIME_FONT_SIZE = 56
TAGLINE_FONT_SIZE = 13
BUTTON_FONT_SIZE = 14

# button geometry / style
BUTTON_HEIGHT = 42
BUTTON_BORDER_WIDTH = 2
BUTTON_BORDER_RADIUS = 21
BUTTON_PADDING_HORIZONTAL = 22
BUTTON_FONT_WEIGHT = 600
BUTTON_PRESSED_PADDING_TOP = 2

# asset filenames
BACKGROUND_FILENAME = "background.png"
CHIME_FILENAME = "chime.wav"
CHIME_VOLUME = 0.9

# error / dialog text
ERROR_MESSAGE_HEADER = "tar0bunny Pomodoro couldn't load these image(s):\n  "
ERROR_MESSAGE_FOOTER = (
    "\n\nMake sure the 'assets' folder (with background.png) sits in the "
    "SAME folder as pomodoro.py."
)
MISSING_FILES_DIALOG_TITLE = "tar0bunny Pomodoro - missing files"

# modes
MODE_FOCUS = "focus"
MODE_BREAK = "break"

# time label geometry, centered in the window
TIME_LABEL_OFFSET_X = 220
TIME_LABEL_WIDTH = 440
TIME_LABEL_HEIGHT = 90
TIME_LABEL_Y = WINDOW_HEIGHT // 2 - TIME_LABEL_HEIGHT // 2
TIME_SHADOW_BLUR_RADIUS = 18

# gaps around the clock
GAP_ABOVE_CLOCK = 40
GAP_BELOW_CLOCK = 20
GAP_ABOVE_BUTTONS = 30
PANEL_PADDING = 30

# session label geometry, stacked above the clock
SESSION_LABEL_OFFSET_X = 180
SESSION_LABEL_WIDTH = 360
SESSION_LABEL_HEIGHT = 48
SESSION_LABEL_Y = TIME_LABEL_Y - SESSION_LABEL_HEIGHT - GAP_ABOVE_CLOCK
SESSION_SHADOW_BLUR_RADIUS = 14
SHADOW_OFFSET_X = 0
SHADOW_OFFSET_Y = 2

# tagline geometry, below the clock
TAGLINE_TEXT = "Stay curious."
TAGLINE_OFFSET_X = 150
TAGLINE_WIDTH = 300
TAGLINE_HEIGHT = 26
TAGLINE_Y = TIME_LABEL_Y + TIME_LABEL_HEIGHT + GAP_BELOW_CLOCK

# button row geometry, below the tagline
BUTTON_ROW_Y = TAGLINE_Y + TAGLINE_HEIGHT + GAP_ABOVE_BUTTONS
START_BUTTON_OFFSET_X = 195
START_BUTTON_WIDTH = 120
RESET_BUTTON_OFFSET_X = 65
RESET_BUTTON_WIDTH = 120
MODE_BUTTON_OFFSET_X = 65
MODE_BUTTON_WIDTH = 130

# button text, plain text, no emoji
START_BUTTON_START_TEXT = "Start"
START_BUTTON_PAUSE_TEXT = "Pause"
RESET_BUTTON_TEXT = "Reset"
MODE_BUTTON_BREAK_TEXT = "Break"
MODE_BUTTON_BREAK_SHORT_TEXT = "Break"
MODE_BUTTON_FOCUS_SHORT_TEXT = "Focus"

# session label text
SESSION_LABEL_FOCUS_TEXT = "Focus Mode"
SESSION_LABEL_BREAK_TEXT = "Break Mode"

# time formatting
TIME_FORMAT = "{:02d}:{:02d}"

# background panel geometry, wraps session label through button row
PANEL_OFFSET_X = 260
PANEL_WIDTH = 520
PANEL_Y = SESSION_LABEL_Y - PANEL_PADDING
PANEL_BOTTOM = BUTTON_ROW_Y + BUTTON_HEIGHT + PANEL_PADDING
PANEL_HEIGHT = PANEL_BOTTOM - PANEL_Y
PANEL_BORDER_RADIUS = 28